package com.nammametro.simulation.trainsim.application.tick;

import com.nammametro.simulation.trainsim.application.TickContext;
import com.nammametro.simulation.trainsim.application.TickHandler;
import com.nammametro.simulation.trainsim.application.TickResult;
import com.nammametro.simulation.trainsim.domain.model.EventType;
import com.nammametro.simulation.trainsim.domain.model.SimulationEvent;
import com.nammametro.simulation.trainsim.domain.model.SimulationState;
import com.nammametro.simulation.trainsim.domain.model.TrainState;
import com.nammametro.simulation.trainsim.domain.model.TrainStatus;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Releases {@link TrainStatus#SCHEDULED} trains into service once the clock reaches their
 * {@link TrainState#scheduledDepartureSeconds()}, generated by a {@code LineSchedule} (first
 * train, last train, headway, count — see {@code trainsim.infrastructure.LineScheduleAssembler}).
 * Runs second in {@code TrainSimulationEngine}'s pipeline, after {@link ClockAdvanceHandler} and
 * before {@link TrainMovementTickHandler} — so a train dispatched this tick is already eligible to
 * begin dwelling/departing (headway-checked against other trains) on the very same tick's movement
 * pass, not a tick later.
 *
 * <p>A schedule's headway already spaces its generated trains' departure times apart; this handler
 * only ever gates a single train's own status by its own scheduled time, so — unlike
 * {@code TrainMovementTickHandler}'s track-occupancy check — it needs no cross-train state.
 */
public class TrainDispatcher implements TickHandler {

    @Override
    public TickResult handle(SimulationState current, TickContext context) {
        long elapsed = current.clock().elapsedSimulationSeconds();
        Instant simTime = current.clock().currentTime();
        long tick = current.clock().currentTick();

        List<TrainState> updated = new ArrayList<>();
        List<SimulationEvent> events = new ArrayList<>();

        for (TrainState train : current.trains()) {
            if (train.status() != TrainStatus.SCHEDULED || elapsed < train.scheduledDepartureSeconds()) {
                updated.add(train);
                continue;
            }

            TrainState dispatched = new TrainState(
                    train.id(), train.code(), train.lineCode(), train.direction(), null,
                    train.previousStationId(), train.previousStationId(), 0, 0, TrainStatus.AT_STATION,
                    train.passengerCount(), train.capacity(), 0, 0,
                    train.scheduledDepartureSeconds(), train.dwellTimeSeconds(), train.maxSpeedKmph(),
                    train.accelerationMps2(), train.brakingRateMps2(),
                    train.scheduledArrivalSeconds(), train.actualArrivalSeconds(), train.actualDepartureSeconds(),
                    train.delaySeconds());
            updated.add(dispatched);
            events.add(new SimulationEvent(tick, simTime, EventType.DISPATCHED, train.id(), train.code(),
                    train.previousStationId(), "%s dispatched into service".formatted(train.code())));
        }

        return new TickResult(current.withTrains(updated), events);
    }
}
